services:
  - type: web
    name: wardizitto-recordings
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
        
