services:
  - type: web
    name: wardizitto-recordings
    env: node
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_PASS_HASH
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BOT_API_BASE
        sync: false
